import React from 'react';
import Typography from '@mui/material/Typography';
import GroupWorkRoundedIcon from '@mui/icons-material/GroupWorkRounded';
import DesignServicesRoundedIcon from '@mui/icons-material/DesignServicesRounded';
import AssessmentRoundedIcon from '@mui/icons-material/AssessmentRounded';
import Stack from '@mui/material/Stack';
import Box from '@mui/material/Box';
import Example from './../../assets/example';


export default function Features() {
  return (

    <div id="features" className="light section">
      {/* <ClusterGraph /> */}
      <Stack spacing={{xs:3}}>
        <Box>
          <Stack direction={{ xs: 'column', md: 'row' }} alignItems="center" justifyContent="space-between">
            {/* <div style={{"flex":1}}><Typography variant="h2" id="features-header">Measure Your Application’s Routing Efficiency</Typography></div>
            <div style={{"flex":1}}><img src="https://res.cloudinary.com/dcgcphyrt/image/upload/v1636132834/index_pcykh1.png"/></div> */}
            <div><Typography variant="h2" id="features-header">Measure Your Application’s Routing Efficiency</Typography></div>
            <div>
              <img style={{"objectFit" : "contain", "height" : "100%", "width" : "100%"}} src={Example}/>
            </div>
          </Stack>
        </Box>
        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={{xs:7}} justifyContent="space-between">
          <div className="feature"><Typography variant="h5" className="feature-header" id="feature-header-1"><GroupWorkRoundedIcon/>Cluster Recommendations</Typography>
          <Typography variant="body1" className="feature-body" id="feature-body-1">Provide detailed cluster recommendations, generated by the Gimbap algorithm, which bundles endpoints together based on similar covariant scores, and displays these recommendations on a Visx-powered dendrogram.</Typography>
          </div>

          <div className="feature"><Typography variant="h5" className="feature-header" id="feature-header-2"><AssessmentRoundedIcon/>Real-Time Endpoint Tracking</Typography>
          <Typography variant="body1" className="feature-body" id="feature-body-2">Monitor and visualize individual endpoints' call time performance to learn more about the usage of each specific route within an application.</Typography>
          </div>

          <div className="feature"><Typography variant="h5" className="feature-header" id="feature-header-3"><DesignServicesRoundedIcon />Simple Setup</Typography>
          <Typography variant="body1" className="feature-body" id="feature-body-3">In just a few minutes, Gimbap can be deployed onto your javascript application. Install the Gimbap NPM package, set up a standard database, and download the front-end client below. Learn more on our Documentation page.</Typography></div>
        </Stack>
      </Stack>
    </div>

  );
}
